name: "Development Workflow"
on:
    push:
        paths-ignore:
            - '.github/workflows/test.yaml'

jobs:
    dockerhub:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                tags: ${{ secrets.DOCKER_USERNAME }}/news-letter:${{ github.sha }}
                push: true
    docker-run:
        runs-on: self-hosted
        needs: dockerhub
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run docker container
              run: docker run -d -p 3000:3000 --name development-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/news-letter:${{ github.sha }}



