name: Staging workflow
on:
    push:
      tags:
        - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
    docker-run:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Run docker container
              run: docker run -d -p 8080:8080 --name test-$(basename ${GITHUB_REF}) ${{ secrets.DOCKER_USERNAME }}/latest
  