name: Staging workflow
on:
    push:
      tags:
        - '[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'

jobs:
    docker-run:
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Pull docker image
              run: docker pull ${{ secrets.DOCKER_USERNAME }}/news-letter:latest
            - name: Run docker container
              run: docker run -d -p 3002:3002 --name test-${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/$(basename ${GITHUB_REF})
  